# Generated by Django 3.1 on 2020-10-17 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('inst', models.CharField(max_length=200)),
                ('dscrb', models.TextField()),
                ('category', models.CharField(choices=[('J', 'Junior'), ('S', 'Senior'), ('P', 'Primary'), ('HS', 'Higher Secondary'), ('All', 'All')], max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='EventRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule', models.CharField(max_length=1000)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='academy.event')),
            ],
        ),
    ]
