# Generated by Django 3.1 on 2020-10-17 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0003_auto_20201016_2307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventrule',
            name='event',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='EventRule',
        ),
    ]
