# Generated by Django 3.1 on 2020-10-18 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0008_result'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuizAns',
        ),
    ]
