# Generated by Django 3.1 on 2020-10-18 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0009_delete_quizans'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizAns',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=1000)),
                ('ques', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='academy.quizque')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='academy.quiz')),
            ],
        ),
    ]
