# Generated by Django 3.1 on 2020-10-19 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0010_quizans'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='time',
            field=models.IntegerField(default=20),
            preserve_default=False,
        ),
    ]
