# Generated by Django 3.1 on 2020-10-30 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0011_quiz_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizans',
            name='ques',
        ),
        migrations.RemoveField(
            model_name='quizans',
            name='quiz',
        ),
        migrations.RemoveField(
            model_name='quizque',
            name='quiz',
        ),
        migrations.RemoveField(
            model_name='result',
            name='quiz',
        ),
        migrations.DeleteModel(
            name='Quiz',
        ),
        migrations.DeleteModel(
            name='QuizAns',
        ),
        migrations.DeleteModel(
            name='QuizQue',
        ),
        migrations.DeleteModel(
            name='Result',
        ),
    ]
